### ISSUE TITLE
 Received message on illegal discovery topic

### ISSUE THREAD

**Issue by JoeMoer222** [Tertiush/bmspace#10]
Hi  I am battling to get mqtt auto discovery, in a fresh install of home assistant, to discover my hubble batteries.
Getting the following type of errors:
2023-05-19 13:13:39.415 WARNING (MainThread) [homeassistant.components.mqtt.discovery] Received message on illegal discovery topic 'homeassistant/sensor/BMS-0153131140211S /Pack_1_Cell_1_Voltage/config'. The topic contains not allowed characters. For more information see https://www.home-assistant.io/docs/mqtt/discovery/#discovery-topic
This in mqtt explorer.
{
  "availability_topic": "bmspace/availability",
  "device": {
    "manufacturer": "BMS Pace",
    "model": "AM-x",
    "identifiers": "bmspace_0153131140211S ",
    "name": "Generic Lithium",
    "sw_version": "P13S120A-12290-1.46T"
  },
  "name": "Pack 1 Cell 1 Voltage",
  "unique_id": "bmspace_0153131140211S _pack_1_v_cell_1",
  "state_topic": "bmspace/pack_1/v_cells/cell_1",
  "unit_of_measurement": "mV"
}
Any suggestions?

**Comment by Tertiush** [comment]
There seems to be a space in the unique ID, that's probably the issue.....

You can manually remove the space in MQTT Explorer and see if its pulls it
in then.

I'll try to address this over the weekend, along with some other
maintenance work

**Comment by JoeMoer222** [comment]
Yes, just my luck that battery number 1 has the problem with the space in it's serial number. Changed the pack order around and now Home Assistant sees all 3 my batteries. This after battling for more than a week to get it to work.Thanks for the quick reply and keep up the good work.

**Comment by Tertiush** [comment]
Fix pushed - Add a check to remove whitespaces in the SN
