### ISSUE TITLE
Request CAN/RS485 communicate with inverter

### ISSUE THREAD

**Issue by kebaotu** [Tertiush/bmspace#16]
Hello
First, I would like to thank for this project, I have successfully read the information from the battery.
Currently, I am using an inverter that supports CAN/RS485 which can communicate with pylontech standard. I also found another project that simulates battery information according to the pylontech standard.
[`link`](https://github.com/juamiso/PYLON_EMU)
I don't know much about coding so I hope you can update the current version to add the function of connecting to the inverter.
Hope you can consider it.
Thank you

**Comment by Tertiush** [comment]
Afraid I wont have time for this. This project is purely based on my interest for the PACE BMS. Sorry.
