### ISSUE TITLE
The command '/bin/sh -c apk add --no-cache python3' returned a non-zero code: 1

### ISSUE THREAD

**Issue by shaundekok** [Tertiush/bmspace#2]
I am unable to add the app-on to home assistant. Get the following Error:

"_The command '/bin/sh -c apk add --no-cache python3' returned a non-zero code: 1_"

I want to test it with my Rentech 48v Lithium.

Currently I am running PBMS Tools and getting the data from the SQLite DB on a 2nd PI running Windows 10 for ARM.

**Comment by Tertiush** [comment]
Have you managed to resolve this? Afraid I'm not an expert on the shell commands, but can do some digging... Let me know
