### ISSUE TITLE
Compatible with Youthpower pack

### ISSUE THREAD

**Issue by jean-luc1203** [Tertiush/bmspace#20]
Hello, this message is to inform you that your code works with batteries:
[YouthPower](https://www.youth-power.net/products/solar-energy-storage-batteries) Rack Module 48V 100AH 4U-5U Lifepo4 Solar Storage Battery

Do you think it is possible to interrogate a 2nd battery connected to the 1st via your code?

**Comment by Tertiush** [comment]
Great stuff thanks. As long as you are plugged into the master battery, any other batteries in the same pack (using the interconnected cable) should be picked up automatically. Is this your setup?

**Comment by jean-luc1203** [comment]
The equipment isn't at my place, it's at a friend's 700 km away. I've just contacted him to ask him to take a photo of his 2 batteries to check that it's connected to the 1st one and that there's a communication cable between the 2 batteries. He'll get back to me in 2 hours.
In the meantime, here's what I got from the YouhtPower topic.
Does it help?

`pi@Onduleur:~/YouthPower$ mosquitto_sub -h 127.0.0.1 -t YouthPower/# -v
YouthPower/v_cells/cell_1 3314
YouthPower/v_cells/cell_2 3315
YouthPower/v_cells/cell_3 3314
YouthPower/v_cells/cell_4 3314
YouthPower/v_cells/cell_5 3315
YouthPower/v_cells/cell_6 3315
YouthPower/v_cells/cell_7 3315
YouthPower/v_cells/cell_8 3314
YouthPower/v_cells/cell_9 3315
YouthPower/v_cells/cell_10 3314
YouthPower/v_cells/cell_11 3315
YouthPower/v_cells/cell_12 3314
YouthPower/v_cells/cell_13 3315
YouthPower/v_cells/cell_14 3314
YouthPower/v_cells/cell_15 3314
YouthPower/t_cells/cell_1 28.1
YouthPower/t_cells/cell_2 28.3
YouthPower/t_cells/cell_3 27.8
YouthPower/t_cells/cell_4 27.9
YouthPower/t_mos 28.8
YouthPower/t_env 29.9
YouthPower/pack/i_pack -4.77
YouthPower/pack/v_pack 49.766
YouthPower/pack/i_cap 94940
YouthPower/pack/soh 102.94
YouthPower/pack/cycles 290
YouthPower/pack/i_full 100000
YouthPower/pack/soc 92
YouthPower/v_cells/cell_1 3314
YouthPower/v_cells/cell_2 3315
YouthPower/v_cells/cell_3 3314
YouthPower/v_cells/cell_4 3314
YouthPower/v_cells/cell_5 3315
YouthPower/v_cells/cell_6 3315
YouthPower/v_cells/cell_7 3315
YouthPower/v_cells/cell_8 3314
YouthPower/v_cells/cell_9 3315
YouthPower/v_cells/cell_10 3314
YouthPower/v_cells/cell_11 3315
YouthPower/v_cells/cell_12 3314
YouthPower/v_cells/cell_13 3314
YouthPower/v_cells/cell_14 3314
YouthPower/v_cells/cell_15 3314
YouthPower/t_cells/cell_1 28.1
YouthPower/t_cells/cell_2 28.3
YouthPower/t_cells/cell_3 27.8
YouthPower/t_cells/cell_4 27.9
YouthPower/t_mos 28.8
YouthPower/t_env 29.9
YouthPower/pack/i_pack -4.87
YouthPower/pack/v_pack 49.765
YouthPower/pack/i_cap 94940
YouthPower/pack/soh 102.94
YouthPower/pack/cycles 290
YouthPower/pack/i_full 100000
YouthPower/pack/soc 92
`
Here's what the attachment looks like with the current topics

![capture_20230721-205001](https://github.com/Tertiush/bmspace/assets/44665500/17b277c8-cf6a-4479-b078-4341b80e6082)

**Comment by Tertiush** [comment]
Are you sure the latest script version is running? Just confirm that as I
don't see "pack_1" as part of the topic, which was introduced when multiple
packs got supported.

**Comment by jean-luc1203** [comment]
![photo_2023-07-21_22-13-03](https://github.com/Tertiush/bmspace/assets/44665500/5fdb6695-3b43-4450-bd51-69d17cab04a2)

here they are, there's an rs485 connection cable between the 2.
In any case, thanks for the answers

**Comment by jean-luc1203** [comment]
You're right. I didn't take the latest version, the one I have is older. Sorry I forgot to update. I'll do it tomorrow at the end of the afternoon and come back to give you some feedback.

**Comment by jean-luc1203** [comment]
Thank you very much, your code works like a charm. I was able to integrate it easily. 
My friend is very happy with your work and mine.

I quoted the source of your code on my forum. It's in French, so if you'd like to have a look, click [here](http://domosimple.eu/forum/thread-280-post-2166.html#pid2166).

![capture_20230722-212603](https://github.com/Tertiush/bmspace/assets/44665500/eec90fab-1c7e-4b4e-92cb-52fed359330b)

![capture_20230722-212628](https://github.com/Tertiush/bmspace/assets/44665500/aadc53b0-f247-405d-b879-6184531f52f6)

it's great

**Comment by Tertiush** [comment]
That's great news, thanks for sharing!
