### ISSUE TITLE
Hardware Info and more documentation

### ISSUE THREAD

**Issue by Norm71** [Tertiush/bmspace#33]
I do have a System from Tewaycell [Tewaycell 48V 200Ah 10Kwh All-in-one Mobile ESS Built-in Hybrid Invert](https://tewaycell.com/products/tewaycell-48v-200ah-10kwh-all-in-one-mobile-ess-built-in-hybrid-inverter?variant=41313098858553) and they provided a RS232 to USB Cable with it.

They also sent the PACEexTool but its completely in Chinese.

Now i found your Home Assistant integration. 😀

Can you explain a bit more how i do get the basic connection?
I think i need to install the USB driver for Linux first on the Homeassistant Raspberry. Is that possible?
Then i have questions for the requirements:
paho_mqtt==1.6.1
PyYAML==6.0.1
pyserial==3.5

I dont know how to get the reuirements.

I have Mosquito MQTT and use it already for my OpenDTU and ESP32

I posted in Power Forum but did not get any answer. So i try directly here.

**Comment by Tertiush** [comment]
Do you have home assistant operating system, or just home assistant core
installed? The addon is meant for operating system.

If you run core then you need to install the dependancies in the
requirements file, change the config file to suite your needs, and finally
run the script manually. If you need to run the script as a system service,
Google will help you out there.

**Comment by Norm71** [comment]
Its Home Assistant Operating System. So with HA OS i dont need the paho_mqtt, PyYAML and pyserial?
So i installed the addon and its running. 
The BMS is connected with the provided Rs232 to USB connector. But how can i verify which port is used (/dev/ttyUSB0) and is there a driver needed?

Thats my protocol:
Hello BMS Pace
Starting up...
Loading options.json
Config: {"mqtt_host": "192.168.17.133", "mqtt_port": 1883, "mqtt_user": "mqtt-user", "mqtt_password": "xxxxxxxxxxxx", "mqtt_ha_discovery": true, "mqtt_ha_discovery_topic": "homeassistant", "mqtt_base_topic": "bmspace", "connection_type": "Serial", "bms_ip": "10.0.0.161", "bms_port": 5000, "bms_serial": "/dev/ttyUSB0", "scan_interval": 5, "debug_output": 0}
Connection Type: Serial
MQTT connected with result code 0
Connecting to BMS...
trying to connect /dev/ttyUSB0
BMS serial error connecting: [Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
Traceback (most recent call last):
  File "/workdir/./bms.py", line 1090, in <module>
    success, data = bms_getVersion(bms)
  File "/workdir/./bms.py", line 656, in bms_getVersion
    success, INFO = bms_request(bms,cid2=constants.cid2SoftwareVersion)
  File "/workdir/./bms.py", line 619, in bms_request
    if not bms_sendData(bms,request):
  File "/workdir/./bms.py", line 118, in bms_sendData
    comms.write(request)
AttributeError: 'bool' object has no attribute 'write'
Script exiting

**Comment by Tertiush** [comment]
Nope you don't need it, HAOS will handle all of that for you. Just Google
how to install addons in home assistant, pretty straightforward.

**Comment by Norm71** [comment]
Add on is installed but I don't get any signal from the USB port. Don't know how to find out which is used in Home assistant

**Comment by Tertiush** [comment]
Go look in the system menu for hardware info or something like that. Should
be usbtty1 or something similar. Case sensitive

**Comment by Norm71** [comment]
Thats it:
Hello BMS Pace
Starting up...
Loading options.json
Config: {"mqtt_host": "192.168.17.133", "mqtt_port": 1883, "mqtt_user": "mqtt-user", "mqtt_password": "xxxxxx", "mqtt_ha_discovery": true, "mqtt_ha_discovery_topic": "homeassistant", "mqtt_base_topic": "bmspace", "connection_type": "Serial", "bms_ip": "10.0.0.161", "bms_port": 5000, "bms_serial": "/dev/ttyACM1", "scan_interval": 5, "debug_output": 0}
Connection Type: Serial
MQTT connected with result code 0
Connecting to BMS...
trying to connect /dev/ttyACM1
BMS serial connected

**Comment by Norm71** [comment]
Sorry can you remove my address out of my reply ? Answered from phone and did not thing about it

**Comment by Norm71** [comment]
It was to early to be happy. That was my Z-Wave Stick. Cable is not listed will try a Waveshare RS232 RS485 to WiFi POE Ethernet Serial Server Converter. 
Is there any Hardware you can recommend?

**Comment by Tertiush** [comment]
Nope sorry, just used what I has laying around.

**Comment by Norm71** [comment]
Solved the config!

So what i have:

1. Batterysysttem: https://tewaycell.com/products/tewaycell-48v-200ah-10kwh-all-in-one-mobile-ess-built-in-hybrid-inverter?variant=41313098858553
2. Rs232to Eth: https://www.waveshare.com/wiki/RS485_TO_WIFI/ETH 

Installed your Addon
![image](https://github.com/Tertiush/bmspace/assets/85446601/ee902cc6-a0b0-4d5a-95f0-35b94c37fdf0)

Configured the Waveshare as follows:
![image](https://github.com/Tertiush/bmspace/assets/85446601/381097da-2e19-46f5-96b9-c19f16180c02)

Afterwards the Addon could connect and i directly retrieved:

> Pack Serial Number: 
> Packs: 1
> Pack 1, Total cells: 16
> Pack 1, V Cell1: 3281 mV
> Pack 1, V Cell2: 3280 mV
> Pack 1, V Cell3: 3281 mV
> Pack 1, V Cell4: 3281 mV
> Pack 1, V Cell5: 3281 mV
> Pack 1, V Cell6: 3280 mV
> Pack 1, V Cell7: 3280 mV
> Pack 1, V Cell8: 3280 mV
> Pack 1, V Cell9: 3280 mV
> Pack 1, V Cell10: 3280 mV
> Pack 1, V Cell11: 3279 mV
> Pack 1, V Cell12: 3279 mV
> Pack 1, V Cell13: 3279 mV
> Pack 1, V Cell14: 3279 mV
> Pack 1, V Cell15: 3279 mV
> Pack 1, V Cell16: 3278 mV
> Pack 1, Cell Max Diff Volt Calc: 3 mV
> Pack 1, Total temperature sensors: 6
> Pack 1, Temp1: 23.7 ℃
> Pack 1, Temp2: 22.0 ℃
> Pack 1, Temp3: 20.3 ℃
> Pack 1, Temp4: 19.5 ℃
> Pack 1, Temp5: 29.8 ℃
> Pack 1, Temp6: 26.4 ℃
> Pack 1, I Pack: -1.17 A
> Pack 1, V Pack: 52.477 V
> Pack 1, I Remaining Capacity: 73750 mAh
> Pack 1, I Full Capacity: 200000 mAh
> Pack 1, SOC: 36.88 %
> Pack 1, Cycles: 15
> Pack 1, Design Capacity: 190000 mAh
> Pack 1, SOH: 105.26 %
> Script running....
> Pack Remaining Capacity: 73750 mAh
> Pack Full Capacity: 200000 mAh
> Pack Design Capacity: 190000 mAh
> Pack SOC: 36.88 %
> Pack SOH: 105.26 %
> Packs for warnings: 1
> Pack 1, warnings: 
> Pack 1, balancing1: 00000000
> Pack 1, balancing2: 00000000
> Publishing HA Discovery topic...

Many thanks for this Addon !!!!!!
