### ISSUE TITLE
paho.mqtt 

### ISSUE THREAD

**Issue by Zodiac-69** [Tertiush/bmspace#38]
Please update mqtt section to accomodate paho.mqtt new requirement - CallbackAPIVersion.VERSION2

**Comment by Tertiush** [comment]
The requriements.txt file installs v1 of paho, so the current code should not fail. If you run it manually with your own paho version 2 I guess there'd be an issue. I won't have time soon to make this change though, only in a future update.

**Comment by Zodiac-69** [comment]
Hi Tertiush
Yes, i used a new install on RP as i have not used your code before.
I did find a way around it by changing line 70 in your code as follow:
#client = mqtt.Client("bmspace")
client = mqtt.Client(mqtt.CallbackAPIVersion.VERSION1, "bmspace")
