### ISSUE TITLE
UFO Battery - hex string in balance state

### ISSUE THREAD

**Issue by LubosD** [Tertiush/bmspace#4]
Hi,
thanks a lot for your work!

Could you please check the docs with regards to [these](https://github.com/Tertiush/bmspace/blob/main/bms.py#L998) [two](https://github.com/Tertiush/bmspace/blob/main/bms.py#L1001) lines? Are they really supposed to be base-8?

I'm getting exceptions because it's trying to parse strings such as `0A` or `0E`. When I change it to base-16, it works OK with my battery pack (UFO Battery 10 kWh).

**Comment by Tertiush** [comment]
Hi, yes it should be. Guess I had 8 bits in my head and somehow thought the base is 8.... 4 bits per Hex so base 16. Pushing a fix now.
