### ISSUE TITLE
Setting Up In Home Assistant

### ISSUE THREAD

**Issue by snaven1** [Tertiush/bmspace#6]
When trying to add this module as per adding via new repository mechanism, current version of home assistant
does not allow the addon. Some parameter configuration is not correct.

**Comment by Tertiush** [comment]
Please check HAs logs for any indication of what the missing parameter is,
otherwise I don't have a lot to go on. Seems to work fine for other users.

**Comment by snaven1** [comment]
Problem resolved ... thanks for quick response. The installed module was not displaying within the addons until I refreshed the browser cache.
