### ISSUE TITLE
Error parsing BMS warning data

### ISSUE THREAD

**Issue by scandiumza** [Tertiush/bmspace#7]
First off, I'd like to thank you for creating and sharing this addon.

I've got a USB to RS232 cable hooked up to one of my two Greenrich U-P5000 batteries and as far as I can tell, the addon is pretty much correctly parsing everything correctly except for the warnings. 

I've attached the complete (and verbose) log output leading up to the parsing error. Hope this helps :)

[bmspace.log](https://github.com/Tertiush/bmspace/files/11465611/bmspace.log)

**Comment by zit501** [comment]
Hi Tertius,

Also thanks from me for this addon.

I posted the same error on PowerForum, which you said to post the error log here. I don't have the logs at hand, and I'm away for a few days. Mine was pretty much the same as @scandiumza, just the hex 0xD character on my Hubble AM-2's.

Thanks

**Comment by Tertiush** [comment]
Found the issue, fix should come tomorrow. Problem was the protocol sometimes adds a INFOFLAG in the byte-stream which shifts the data out. I've added logic to test for this.

Will also try to reduce the length of reported warning info as it sometimes hits HA's character limit.

**Comment by Tertiush** [comment]
Update pushed. Please test and let me know of there's still issues. thanks

**Comment by scandiumza** [comment]
Hi Tertius, 

Thanks for getting this sorted out so quickly, I've updated and can confirm that a) the errors are gone and b) I'm now able to see the warnings in HA. This issue looks to be resolved, so I'll be closing this issue 😊
